---
-   name: Provision manager
    hosts: manager
    remote_user: root
    roles:
      - swap
      - docker
      - swarm-manager

-   name: Provision worker
    hosts: workers
    remote_user: root
    roles:
      - swap
      - docker
      - swarm-worker

- name: Set labels
  hosts: manager
  remote_user: root
  roles:
      - role: swarm-labels
        vars:
          hostname: "{{ worker_1_hostname }}"
          labels:
            worker: worker-1
          hostname1: "{{ frontend_1_hostname }}"
          labels1:
            worker: frontend-1  
          hostname2: "{{ worker_2_hostname }}"
          labels2:
            worker: worker-2
          hostname3: "{{ monitoring_hostname }}"
          labels3:
            worker: monitoring
          # hostname2: "{{ parser_hostname }}"
          # labels2:
          #   parser: parser
